apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cull-deployment
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: cull-pod
    spec:
      containers:
        - name: cull-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/sh
            - -c
          args: ['python /srv/cull/cull_idle_servers.py --timeout={{ .Values.cull_timeout }} --cull_every={{ .Values.cull_every }} --url=http://${HUB_SERVICE_HOST}:${HUB_SERVICE_PORT}/hub']
          env:
          - name: JPY_API_TOKEN
            valueFrom:
              configMapKeyRef:
                name: hub-config
                key: auth.jhub-token.cull
